// ebpf/loader/main.go
// Go eBPF loader — attaches compiled eBPF probes to the running kernel
// and exports events to Kafka / Redis for downstream processing.
//
// Requires: Linux kernel ≥ 5.15 with CO-RE support, must run as root.
// Usage: sudo ./kognos-loader [--kafka localhost:9092] [--topic ebpf-flows]

package main

import (
	"encoding/binary"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/perf"
	"github.com/cilium/ebpf/rlimit"
	"go.uber.org/zap"
)

// FlowEvent mirrors the C struct flow_event from network_flow.c
type FlowEvent struct {
	SrcIP       uint32
	DstIP       uint32
	SrcPort     uint16
	DstPort     uint16
	Bytes       uint64
	TimestampNS uint64
	PID         uint32
	TID         uint32
	Comm        [16]byte
	Protocol    uint8
	Pad         [3]byte
}

func (fe FlowEvent) SrcIPStr() string {
	b := make([]byte, 4)
	binary.BigEndian.PutUint32(b, fe.SrcIP)
	return fmt.Sprintf("%d.%d.%d.%d", b[0], b[1], b[2], b[3])
}

func (fe FlowEvent) DstIPStr() string {
	b := make([]byte, 4)
	binary.BigEndian.PutUint32(b, fe.DstIP)
	return fmt.Sprintf("%d.%d.%d.%d", b[0], b[1], b[2], b[3])
}

// bpfObjects holds all eBPF maps and programs loaded from the compiled .o file.
// Generated by bpf2go / ebpf-go toolchain.
type bpfObjects struct {
	TraceTcpSend *ebpf.Program `ebpf:"trace_tcp_send"`
	FlowEvents   *ebpf.Map    `ebpf:"flow_events"`
}

func (o *bpfObjects) Close() {
	if o.TraceTcpSend != nil {
		o.TraceTcpSend.Close()
	}
	if o.FlowEvents != nil {
		o.FlowEvents.Close()
	}
}

func main() {
	kafkaAddr := flag.String("kafka", getEnv("KAFKA_BOOTSTRAP", "localhost:9092"), "Kafka bootstrap address")
	kafkaTopic := flag.String("topic", getEnv("KAFKA_TOPIC_FLOWS", "ebpf-flows"), "Kafka topic for flow events")
	redisURL := flag.String("redis", getEnv("REDIS_URL", "redis://localhost:6379"), "Redis URL")
	flag.Parse()

	logger, _ := zap.NewProduction()
	defer logger.Sync()

	logger.Info("KOGNOS eBPF Loader starting",
		zap.String("kafka", *kafkaAddr),
		zap.String("topic", *kafkaTopic),
	)

	// Remove memlock limit (required for eBPF maps on kernels < 5.11)
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatalf("removing memlock: %v", err)
	}

	// Load compiled eBPF object (generated from network_flow.c via bpf2go)
	objs := bpfObjects{}
	spec, err := ebpf.LoadCollectionSpec("ebpf/probes/network_flow.o")
	if err != nil {
		log.Fatalf("loading eBPF spec: %v\n"+
			"Hint: run 'make build-ebpf' first (requires Linux + clang)", err)
	}

	if err := spec.LoadAndAssign(&objs, nil); err != nil {
		log.Fatalf("loading eBPF objects: %v", err)
	}
	defer objs.Close()

	// Attach kprobe to tcp_sendmsg
	kp, err := link.Kprobe("tcp_sendmsg", objs.TraceTcpSend, nil)
	if err != nil {
		log.Fatalf("attaching kprobe/tcp_sendmsg: %v", err)
	}
	defer kp.Close()
	logger.Info("kprobe/tcp_sendmsg attached")

	// Create perf reader for the ring buffer
	rd, err := perf.NewReader(objs.FlowEvents, os.Getpagesize()*64)
	if err != nil {
		log.Fatalf("creating perf reader: %v", err)
	}
	defer rd.Close()

	// Initialise Kafka exporter
	exporter, err := NewKafkaExporter(*kafkaAddr, *kafkaTopic, *redisURL)
	if err != nil {
		log.Fatalf("creating Kafka exporter: %v", err)
	}
	defer exporter.Close()

	// Handle SIGINT / SIGTERM for graceful shutdown
	stopc := make(chan os.Signal, 1)
	signal.Notify(stopc, syscall.SIGINT, syscall.SIGTERM)

	logger.Info("Reading eBPF events — press Ctrl+C to stop")

	go func() {
		<-stopc
		logger.Info("Shutting down...")
		rd.Close()
	}()

	stats := struct{ received, exported, dropped int64 }{}
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()

	go func() {
		for range ticker.C {
			logger.Info("Stats",
				zap.Int64("received", stats.received),
				zap.Int64("exported", stats.exported),
				zap.Int64("dropped", stats.dropped),
			)
		}
	}()

	for {
		record, err := rd.Read()
		if err != nil {
			if perf.IsClosed(err) {
				break
			}
			logger.Warn("perf read error", zap.Error(err))
			continue
		}

		stats.received++

		if record.LostSamples > 0 {
			stats.dropped += int64(record.LostSamples)
			logger.Warn("lost samples", zap.Uint64("count", record.LostSamples))
		}

		if err := exporter.Export(record.RawSample); err != nil {
			logger.Error("export error", zap.Error(err))
		} else {
			stats.exported++
		}
	}

	logger.Info("KOGNOS eBPF loader exited cleanly")
}

func getEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
